# Generated by Django 3.2.8 on 2021-11-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=50)),
                ('normal', models.FloatField()),
                ('very_mild', models.FloatField()),
                ('mild', models.FloatField()),
                ('moderate', models.FloatField()),
                ('img_url', models.CharField(max_length=300)),
            ],
        ),
    ]
